export const homescreenjson = [
  {
    id: 1,
    clint_name: "THbred 1",
    Active_Picklist: 100,
    Packed: 10,
    Shipped: 5,
  },

  {
    id: 2,
    clint_name: "THbred 1",
    Active_Picklist: 100,
    Packed: 10,
    Shipped: 5,
  },

  {
    id: 3,
    clint_name: "THbred 3",
    Active_Picklist: 100,
    Packed: 10,
    Shipped: 5,
  },
];

export const data = {
  CURR_VERSION: "1.0",
  data: [
    {
      CLIENT_ID: "CAR800",
      CLIENT_NAME: "Carnegie Fabrics LLC",
      TOTAL_ORDER: "2",
      TOTAL_PICKED: 0,
    },
    {
      CLIENT_ID: "ERC110",
      CLIENT_NAME: "Erica Shamrock",
      TOTAL_ORDER: "31",
      TOTAL_PICKED: 0,
    },
    {
      CLIENT_ID: "NAS890",
      CLIENT_NAME: "NASSIMI",
      TOTAL_ORDER: "5",
      TOTAL_PICKED: 0,
    },
    {
      CLIENT_ID: "SPL780",
      CLIENT_NAME: "Special-Lite",
      TOTAL_ORDER: "4",
      TOTAL_PICKED: 0,
    },
  ],
  message: "Order found for 4 clients.",
  success: 1,
};

export const itemData = [
  {
    COMMENT_TEXT: "",
    ITEM_DESC: "ODYSSEY4 MEMO",
    ITEM_NO: "6000/4/SM",
    LINE_NO: "2",
    LOCATION: [
      {
        STOCK_AREA: "BG",
        LOCATION: "BG-C009E",
        ON_HAND: "64",
        PLANT_CODE: "10",
        BIN_LOC: "C009E",
      },
      {
        STOCK_AREA: "BR",
        LOCATION: "BR-K007A",
        ON_HAND: "140",
        PLANT_CODE: "10",
        BIN_LOC: "K007A",
      },
      {
        STOCK_AREA: "BR",
        LOCATION: "BR-K007A",
        ON_HAND: "140",
        PLANT_CODE: "10",
        BIN_LOC: "K007A",
      },
    ],
    QTY_ORDER: "1",
    QTY_PICKED: "",
    RESTOCK_REQUEST: { FROM_LOCATION: "", TO_LOCATION: "" },
    SELECTED_LOCATION: "BG-C009E",
    STATUS: "",
  },
  {
    COMMENT_TEXT: "",
    ITEM_DESC: "ODYSSEY 5 MEMO",
    ITEM_NO: "6000/5/SM",
    LINE_NO: "3",
    LOCATION: [
      {
        STOCK_AREA: "BG",
        LOCATION: "BG-C009E",
        ON_HAND: "64",
        PLANT_CODE: "10",
        BIN_LOC: "C009E",
      },
      {
        STOCK_AREA: "BR",
        LOCATION: "BR-K007A",
        ON_HAND: "140",
        PLANT_CODE: "10",
        BIN_LOC: "K007A",
      },
    ],
    QTY_ORDER: "1",
    QTY_PICKED: "",
    RESTOCK_REQUEST: { FROM_LOCATION: "", TO_LOCATION: "" },
    SELECTED_LOCATION: "BF-K017B",
    STATUS: "",
  },
  {
    COMMENT_TEXT: "",
    ITEM_DESC: "ODYSSEY 6 MEMO",
    ITEM_NO: "6000/6/SM",
    LINE_NO: "4",
    LOCATION: [
      {
        STOCK_AREA: "BG",
        LOCATION: "BG-C009E",
        ON_HAND: "64",
        PLANT_CODE: "10",
        BIN_LOC: "C009E",
      },
      {
        STOCK_AREA: "BR",
        LOCATION: "BR-K007A",
        ON_HAND: "140",
        PLANT_CODE: "10",
        BIN_LOC: "K007A",
      },
    ],
    QTY_ORDER: "1",
    QTY_PICKED: "",
    RESTOCK_REQUEST: { FROM_LOCATION: "", TO_LOCATION: "" },
    SELECTED_LOCATION: "BF-K017B",
    STATUS: "",
  },
  {
    COMMENT_TEXT: "",
    ITEM_DESC: "ODYSSEY 2 MEMO",
    ITEM_NO: "6000/2/SM",
    LINE_NO: "1",
    LOCATION: [
      {
        STOCK_AREA: "BG",
        LOCATION: "BG-C009E",
        ON_HAND: "64",
        PLANT_CODE: "10",
        BIN_LOC: "C009E",
      },
      {
        STOCK_AREA: "BR",
        LOCATION: "BR-K007A",
        ON_HAND: "140",
        PLANT_CODE: "10",
        BIN_LOC: "K007A",
      },
    ],
    QTY_ORDER: "1",
    QTY_PICKED: "",
    RESTOCK_REQUEST: { FROM_LOCATION: "", TO_LOCATION: "" },
    SELECTED_LOCATION: "BF-K017I",
    STATUS: "",
  },
  {
    COMMENT_TEXT:
      "DO NOT SEND ONLY RETURN LABEL!!IF ALL ITEMS ARE STOCK OUTS, STOCK OUT THE RETURN LABEL.",
    ITEM_DESC: "USPS RETURN LABEL",
    ITEM_NO: "907800/4/ST",
    LINE_NO: "7",
    LOCATION: [
      {
        STOCK_AREA: "BG",
        LOCATION: "BG-C009E",
        ON_HAND: "64",
        PLANT_CODE: "10",
        BIN_LOC: "C009E",
      },
      {
        STOCK_AREA: "BR",
        LOCATION: "BR-K007A",
        ON_HAND: "140",
        PLANT_CODE: "10",
        BIN_LOC: "K007A",
      },
    ],
    QTY_ORDER: "1",
    QTY_PICKED: "",
    RESTOCK_REQUEST: { FROM_LOCATION: "", TO_LOCATION: "" },
    SELECTED_LOCATION: "BF-L003A",
    STATUS: "",
  },
  {
    COMMENT_TEXT: "",
    ITEM_DESC: "BESPOKE 6 MEMO",
    ITEM_NO: "6244/6/SM",
    LINE_NO: "5",
    LOCATION: [
      {
        STOCK_AREA: "BG",
        LOCATION: "BG-C009E",
        ON_HAND: "64",
        PLANT_CODE: "10",
        BIN_LOC: "C009E",
      },
      {
        STOCK_AREA: "BR",
        LOCATION: "BR-K007A",
        ON_HAND: "140",
        PLANT_CODE: "10",
        BIN_LOC: "K007A",
      },
    ],
    QTY_ORDER: "1",
    QTY_PICKED: "",
    RESTOCK_REQUEST: { FROM_LOCATION: "", TO_LOCATION: "" },
    SELECTED_LOCATION: "BF-P018G",
    STATUS: "",
  },
  {
    COMMENT_TEXT: "",
    ITEM_DESC: "BESPOKE 9 MEMO",
    ITEM_NO: "6244/9/SM",
    LINE_NO: "6",
    LOCATION: [
      {
        STOCK_AREA: "BG",
        LOCATION: "BG-C009E",
        ON_HAND: "64",
        PLANT_CODE: "10",
        BIN_LOC: "C009E",
      },
      {
        STOCK_AREA: "BR",
        LOCATION: "BR-K007A",
        ON_HAND: "140",
        PLANT_CODE: "10",
        BIN_LOC: "K007A",
      },
    ],
    QTY_ORDER: "1",
    QTY_PICKED: "",
    RESTOCK_REQUEST: { FROM_LOCATION: "", TO_LOCATION: "" },
    SELECTED_LOCATION: "BF-P018G",
    STATUS: "",
  },
];

export const orders = {
  data: [
    {
      COMPLETE_PICKUP: "N",
      ISREVERTABLE: 1,
      IS_DRAFT_ORDER: 1,
      ORDER_DATE_TIME: "2024-02-05 17:20:00",
      ORDER_HOLD_CD: "",
      ORDER_NO: "395282",
      ORDER_SUFFIX: "0",
      READY_FOR_SHIP: "N",
      TOTAL_LINES: "7",
      TOTAL_PIECES: "7",
    },
    {
      COMPLETE_PICKUP: "N",
      ISREVERTABLE: 0,
      IS_DRAFT_ORDER: 0,
      ORDER_DATE_TIME: "2024-02-08 18:16:00",
      ORDER_HOLD_CD: "",
      ORDER_NO: "395751",
      ORDER_SUFFIX: "0",
      READY_FOR_SHIP: "N",
      TOTAL_LINES: "5",
      TOTAL_PIECES: "25",
    },
  ],

  message: "2 orders found for CAR800",
  success: 1,
};
