// Types for SignUp

//Types for Login
export const LOADER = 'LOADER';
export const USER_DATA = 'USER_DATA';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';

export const USER_LOGIN_MESSAGE = 'USER_LOGIN_MESSAGE';
export const USER_NAME = 'USER_NAME';
export const USER_EMPONO = 'USER_EMPONO';
export const USER_LOGIN_TYPE = 'USER_LOGIN_TYPE';
export const USER_LOGGED_OUT = 'USER_LOGGED_OUT';

export const VALUE_CHANGE_INC = 'VALUE_CHANGE_INC';
export const VALUE_CHANGE_DIC = 'VALUE_CHANGE_DIC';
export const TIME_LOG = 'TIME_LOG';
export const SHIFT_LOG = 'SHIFT_LOG';
export const HOME_SCREEN_DATA = 'HOME_SCREEN_DATA';
export const ORDER_SCREEN_DATA = 'ORDER_SCREEN_DATA';
export const ORDER_ITEM_DATA = 'ORDER_ITEM_DATA';
export const ORDER_DATE = 'ORDER_DATE';
export const CLEAR_DATA = 'CLEAR_DATA';
export const ORDER_READY_TO_SHIPED = 'ORDER_READY_TO_SHIPED';
export const BARCODE_VALUE = 'BARCODE_VALUE';
export const READY_TO_SHIPORDERS = 'READY_TO_SHIPORDERS';
export const LABEL_PRINTED_ORDERS = 'LABEL_PRINTED_ORDERS';
export const PICKUP_COMPLETED = 'PICKUP_COMPLETED';
export const CURRENT_VERSION = 'CURRENT_VERSION';
export const BARCODE_DATA = 'BARCODE_DATA';
export const LANGUAGE_TYPE = 'LANGUAGE_TYPE';
